<?php

namespace app\models\Headerex;

use app\models\ImageManager;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "headerex".
 *
 * @property int $id
 * @property string $date
 * @property string $title
 * @property string $description
 * @property string $date_begin
 */
class Headerex extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'headerex';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date_begin'], 'safe'],
            [['date', 'title', 'description'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date' => 'Дни выставки',
            'title' => 'Название',
            'description' => 'Описание',
            'date_begin' => 'Дата начала',
        ];
    }
    public function getImages()
    {
        return $this->hasMany(ImageManager::className(), ['item_id' => 'id'])->andWhere(['class'=>self::tableName()])->orderBy('sort');
    }
    public function getImagesLinks()
    {
        return ArrayHelper::getColumn($this->images,'imageUrl');
    }
    public function getImagesLinksData()
    {
        return ArrayHelper::toArray($this->images,[
                ImageManager::className() => [
                    'caption'=>'name',
                    'key'=>'id',
                ]]
        );
    }
    public function getImages1()
    {
        return $this->hasMany(ImageManager::className(), ['item_id' => 'id'])->andWhere(['class'=>'logo'])->orderBy('sort');
    }
    public function getImagesLinks1()
    {
        return ArrayHelper::getColumn($this->images1,'imageUrl');
    }
    public function getImagesLinksData1()
    {
        return ArrayHelper::toArray($this->images1,[
                ImageManager::className() => [
                    'caption'=>'name',
                    'key'=>'id',
                ]]
        );
    }

    public function beforeDelete()
    {
        if ($this->getImages()){
            foreach ($this->images as $one){
                unlink(Yii::getAlias('@images').'/headerex/'. $one->name);
            }
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public static function getIds()
    {
        return  self::find()->select('id')->orderBy('id DESC')->one();
    }
}
